"""empty message

Revision ID: 85a0a0340eb0
Revises: 2c4ac54e91fd
Create Date: 2018-09-29 17:56:34.833118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a0a0340eb0'
down_revision = '2c4ac54e91fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tt', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tt')
    # ### end Alembic commands ###
